apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: gogs 
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  rules:
    - http:
        paths:
          - path: /gogs
            pathType: Prefix
            backend:
              service:
                name: gogs-svc
                port:
                  number: 3000
