apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: wekan-db
  name: wekan-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wekan-db
  template:
    metadata:
      labels:
        app: wekan-db
    spec:
      containers:
      - image: mongo:5.0.15
        name: mongo
        ports:
          - containerPort: 27017
            name: db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: wekan-db-credentials 
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wekan-db-credentials
              key: password
        volumeMounts:
          - name: "data"
            mountPath: "/data/db"
      volumes:
        - name: "data"
          persistentVolumeClaim:
            claimName: wekan-db 