Vagrant.configure("2") do |config|
  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.define "master" do |machine|
    machine.vm.box = "debian/stretch64"
    machine.vm.provider "libvirt" do |vb|
      vb.qemu_use_session = false
      vb.memory = "1024"
    end
  end

  config.vm.define "node-a" do |machine|
    machine.vm.box = "debian/stretch64"
    machine.vm.provider "libvirt" do |vb|
        vb.memory = "1024"

    end
  end

  config.vm.define "node-b" do |machine|
    machine.vm.box = "debian/stretch64"
    machine.vm.provider "libvirt" do |vb|
        vb.memory = "1024"

    end
  end
end
