version: '3'
services:
  rethinkdb:
    image: rethinkdb:latest
    volumes:
      - ./rethinkdb_data:/data
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"

  redis:
    image: redis:latest
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"

