Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.provider :libvirt do |vb|
    vb.memory = 512
    vb.cpus = 1
  end

  config.vm.network :private_network, ip: "192.168.33.11"
end
