Vagrant.configure("2") do |config| 
  config.vm.network :private_network, ip: "192.168.56.13"
  
  boxProvider = "debian/stretch64"
  
  virtualizationProvider = :libvirt
  config.vm.define "etcd-a" do |machine|
    machine.vm.box = boxProvider
    machine.vm.provider virtualizationProvider do |m|
      m.memory = 256
      m.cpus = 1
    end
  end

  config.vm.define "etcd-b" do |machine|
    machine.vm.box = boxProvider
    machine.vm.provider virtualizationProvider do |m|
      m.memory = 256
      m.cpus = 1
    end
  end

  config.vm.define "etcd-c" do |machine|
    machine.vm.box = boxProvider
    machine.vm.provider virtualizationProvider do |m|
      m.memory = 256
      m.cpus = 1
    end
  end
  
end
