apiVersion: v1
kind: Service
metadata:
  name: gogs
  labels:
    app: gogs
spec:
  type: ClusterIP 
  ports:
    - name: db
      port: 5432
    - name: web
      port: 3000 
  selector:
    app: gogs
