apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-db
  namespace: gogs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity: 
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/gogs/db"
