Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider :virtualbox do |machine|
    machine.memory = 3000
    machine.cpus = 1
  end 
  config.vm.network :private_network, ip: "192.168.57.13"
end
