- name: Containers
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: Low level container
      apt:
        name: runc
        state: present
    - name: Container daemon present
      apt:
        name: containerd
        state: present
    - name: Lxc present
      apt:
        name: lxc
        state: present 
    - name: Container cli tool present
      apt:
        name: podman
        state: present
    - name: Checkpoint restore in user space
      apt:
        name: criu
        state: present
    - name: Minikube
      shell:
        cmd: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64
          rm minikube-linux-amd64  
        creates: /usr/local/bin/minikube
    - name: Kubectl
      shell:
        cmd: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        creates: /usr/local/bin/kubectl
