apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-db-claim
  namespace: gogs
spec:
  storageClassName: ebs-sc 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
