apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: wekan 
  name: wekan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wekan
  template:
    metadata:
      labels:
        app: wekan
    spec:
      containers:
      - image: wekanteam/wekan 
        name: web
        ports:
          - containerPort: 8080
            name: web
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: wekan-db-credentials
              key: url
        - name: PORT
          valueFrom:
            configMapKeyRef:
                name: wekan-web-config
                key: port
        - name: ROOT_URL
          valueFrom:
            configMapKeyRef:
              name: wekan-web-config
              key: rootURL
      - image: mongo:5.0.15
        name: mongo
        ports:
          - containerPort: 27017
            name: db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: wekan-db-credentials 
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wekan-db-credentials
              key: password
        volumeMounts:
          - name: "data"
            mountPath: "/data/db"
      volumes:
        - name: "data"
          persistentVolumeClaim:
            claimName: wekan-db 